name: Build

on:
  push:
    branches: [ "trunk" ]
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.16.0'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez libdbus-1-dev
          cargo install --locked cargo-xwin cargo-zigbuild

      - name: Install jextract
        shell: bash
        run: |
          mkdir -p $HOME/.jextract
          curl -L "https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz" -o jextract_bundle.tar.gz
          tar -xzf jextract_bundle.tar.gz -C $HOME/.jextract --strip-components=1
          echo "$HOME/.jextract/bin" >> $GITHUB_PATH

      - name: Run Build and Platform Package
        run: ./gradlew build -Pci=true -x test --no-daemon

      - name: Upload Platform Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btleplug4j
          path: build/libs/*.jar

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bluez libdbus-1-dev

      - name: Install jextract
        run: |
          wget https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
          tar -xvf openjdk-22-jextract+6-47_linux-x64_bin.tar.gz
          
          echo "$GITHUB_WORKSPACE/jextract-22/bin" >> $GITHUB_PATH

      - name: Run vHCI Integration Test
        run: ./gradlew test -PrunTest=true
